site_name: AIRBDS AI-Readiness Dataset Scoring Metric
site_url: https://AIBIO-UK.github.io/airbds-metric-tutorial/
nav:
    - About: index.md
    - Course Content:
      - "1. Getting Started — Choose Your Format": chapters/chapter_01.md
      - "2. CSV Walkthrough (Beginner)": chapters/chapter_02_csv.md
      - "3. YAML Walkthrough (Intermediate)": chapters/chapter_03_yaml.md
      - "References": chapters/references.md
    - "Further Resources": follow_up_training.md

theme:
  name: material
  logo: assets/images/aibio-uk-logo.png
  favicon: assets/images/elixir_favicon.ico
  custom_dir: overrides
  features:
    - navigation.top
    - navigation.footer
    - toc.integrate
  font:
    text: Open Sans

repo_name: AIBIO-UK/airbds-metric-tutorial
repo_url: https://github.com/AIBIO-UK/airbds-metric-tutorial
edit_uri: edit/main/docs/

plugins:
  - tags:
      tags_file: keywords.md
  - search
  - bibtex:
      bib_file: "references.bib"
  - mkdocs-video

copyright: By the AIRBDS Working Group, AIBIO-UK (CC BY-SA 4.0) &middot; Built with the <a href="https://doi.org/10.5281/zenodo.7913092">ELIXIR Training Lesson Template</a> (CC BY-SA 4.0)

markdown_extensions:
  - abbr
  - def_list
  - footnotes
  - tables
  - admonition
  - codehilite:
      guess_lang: false
  - sane_lists
  - smarty
  - toc:
      toc_depth: 3
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - neoteroi.cards
  - addbioschemas

extra_css:
  - stylesheets/extra.css
  - stylesheets/neoteroi-mkdocs.css
